### ISSUE TITLE
Checkup Meeting Checklist

### ISSUE THREAD

**Issue by thomashermine** [nextmoov/nextmoov#43]
We're sometimes having Checkup Meetings with team members (especially interns).
But :

- We tend to do these in an informal (that's cool) but sometimes unstructured (less cool) way, and sometimes forget some important questions (not cool at all)
- It's quite inevitably a stressful exercice that some would like to prepare
- We sometimes forget to do these w/ more senior team members

To fix this, I'd like to introduce a new page on the main repository: 
- giving a canvas of questions for theses interview
- enforcing a schedule for these
- insisting on the ability for anyone to call for a checkup meeting anytime.

As with all stuff nextmoov, this canvas should be open & built all together :-)

Following is a first draft ("pièce à casser"), open for discussion :-) 
Can't wait to read your feedback <3 

---

~~We strongly believe happy people are the best ingredients for an happy team.~~

Wait, what? You're not a fucking ingredient! You're a person !

And we really hope you're having a good time with us. 
Not because we're some kinds of philanthropists — but simply because otherwise, you won't make good stuff 🤷‍♂️

We know 2 things :

- Time flies by fast around here
- Evaluation is a tough exercise for both people

That's why :

- We built this form to help both of us ask the rights question during the Checkup Meeting
- You'll have a monthly checkup the 6 first months of work with us, yearly afterwards
- You can ask to have a non-scheduled checkups any time.

This form is only here to facilitate the conversation.
Let's discuss frankly together and see what we can improve!

Ho, one last thing : there is one trap question... Will you spot it?

### Team Spirit

- How are you feeling in the team?
- Did we did anything that upsetted you?
- Did you feel uncomfortable in the team at anytime? If so, why?

### Tools & Conventions

- How do you feel regarding our tools?
- How do you feel regarding our conventions?
- Do we have too much conventions? Or too little?

### Projects & Technologies

- How do you feel regarding the projects you are working on?
- How do you feel regarding our choice to be a JS-only company?

### Team Spirit

- Are you living by our DNA?
- How do you fit in the team?

### Tools & Conventions

- Are you following all our conventions?
- How many meetings did you attend? Is that enough?

### Projects & Technologies

- How senior are you regarding the field you're in ? (back, front, design)
- How much progress did you make since the latest evaluation?
- What are the next things you want to learn?

**Comment by utilisatrice42** [comment]
Maybe adding something about delay for booking this "evaluation" ? This way, people can do, if they want, some introspection about the different questions. 

I think for an intern it can be usefull to have an external point of view about them comportemental attitude and tech skills and also about the future. For instance, views (from a specialist (tech or not) aka other person at nextmoov) about orientations in their field.

**Comment by fhalin** [comment]
Here are some proposed arrangements:

----

~~We strongly believe happy people are the best ingredients for a happy team.~~

Wait, what? You're not a fucking ingredient! You're a person !

And we really hope you're having a good time with us. 
Not because we're some kinds of philanthropists — but simply because otherwise, you won't make good stuff 🤷‍♂️

We know 2 things :

- Time flies by fast around here
- Evaluation is a tough exercise for both people

That's why :

- We built this form to help both of us ask the rights question during the Checkup Meeting
- You'll have a monthly checkup the 6 first months of work with us, yearly afterwards
- You can ask to have a non-scheduled checkups any time.

This form is only here to facilitate the conversation.
Let's discuss frankly together and see what we can improve!

Ho, one last thing : there is one trap question... Will you spot it?

## How is nextmoov doing?

### Team Spirit

- How are you feeling in the team?
- Did we did anything that upsetted you?
- Did you feel uncomfortable in the team at anytime? If so, why?

### Tools & Conventions

- How do you feel regarding our tools?
- How do you feel regarding our conventions?
- Do we have too much conventions? Or too little?

### Projects & Technologies

- How do you feel regarding the projects you are working on?
- How do you feel regarding our choice to be a JS-only company?

## How are you doing?

### Team Spirit

- Are you living by our DNA?
- How do you fit in the team?

### Tools & Conventions

- Are you following all our conventions?
- How many meetings did you attend? Is that enough?

### Projects & Technologies

- How senior are you regarding the field you're in ? (back, front, design)
- How much progress did you make since the latest evaluation?
- What are the next things you want to learn?

**Comment by fhalin** [comment]
@thomashermine @utilisatrice42 I created a dedicated PR #45 to allow for easier modification of the proposed text :)

**Comment by thomashermine** [comment]
@utilisatrice42 I've added your suggestion about "warning delay" on the related PR :-)

@all : Could you have a look and potentially approve the PR?
https://github.com/nextmoov/nextmoov/blob/fhalin-patch-2/onboarding/Checkup_Meeting_Checklist.md
